packages:
  - apps/*
  - packages/*

catalogMode: prefer

catalog:
  "@types/node": ^24.12.3
  "@types/react": ^19.2.0
  "@types/react-dom": ^19.2.0
  typescript: ^6.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  react: ^19.2.0
  react-dom: ^19.2.0
  zod: ^4.4.3
  vitest: ^4.1.10
  "@cloudflare/vitest-pool-workers": ^0.21.3
  "@fontsource-variable/geist": ^5.3.0
  "@fontsource-variable/geist-mono": ^5.3.0
  dodopayments: 2.48.0
  posthog-js: 1.418.16
  "@posthog/react": 1.10.4
  sonner: ^2.0.8

overrides:
  vite: "catalog:"

allowBuilds:
  core-js: false
  esbuild: true
  lightningcss: true
  sharp: true
  workerd: true
