from pathlib import Path
import html,json
p=Path(__file__).resolve().parent;items=sorted(json.loads((p/'content.json').read_text()),key=lambda i:i['publish_order']);esc=html.escape
cards=[]
for i in items:
 id=i['id'];typ=i['format'];n=i['publish_order']
 media=f'<video controls playsinline preload="metadata" poster="{id}/cover.jpg" src="{id}/reel.mp4"></video>' if typ=='reel' else f'<div class="carousel" data-folder="{id}" data-slide="1"><img src="{id}/slide-01.png" alt="{esc(i["slides"][0]["title"])}"><div class="controls"><button onclick="slide(this,-1)" aria-label="Previous slide">←</button><span>1 / 5</span><button onclick="slide(this,1)" aria-label="Next slide">→</button></div></div>'
 download=f'<a href="{id}/reel.mp4" download>Download reel ↗</a>' if typ=='reel' else ' '.join(f'<a href="{id}/slide-{s:02}.png" download>Slide {s}</a>' for s in range(1,6))
 cards.append(f'''<article data-type="{typ}" id="{id}"><div class="media">{media}</div><div class="info"><p class="eyebrow">PIECE {n:02} · {('10-SECOND REEL' if typ=='reel' else '5-SLIDE CAROUSEL')}</p><h2>{esc(i['title'])}</h2><p class="angle">{esc(i['angle'])}</p><p><strong>Opening:</strong> {esc(i['hook'])}</p><details><summary>Caption & publishing files</summary><pre>{esc(i['caption'])}</pre><div class="downloads">{download}<a href="{id}/caption.txt" download>Caption</a></div></details><p class="metric">Watch: {esc(i['metric'])}</p></div></article>''')
css='''@font-face{font-family:Nunito;src:url(assets/nunito.woff2);font-weight:200 1000}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;background:#fffbf4;color:#302e2b;font-family:Nunito,system-ui}header{padding:60px max(28px,calc((100vw - 1140px)/2)) 38px;background:#eeeede;border-bottom:1px solid #d7d6c9}.eyebrow{font-size:12px;letter-spacing:1.6px;font-weight:800;color:#52664c}h1{font-size:clamp(34px,5vw,64px);line-height:1.05;max-width:800px;margin:16px 0}header p{max-width:740px;font-size:18px;line-height:1.5}a{color:#42553d;text-underline-offset:4px}nav{display:flex;flex-wrap:wrap;gap:12px;margin:25px 0 0}button,.pill{padding:10px 18px;border-radius:25px;border:1px solid #88957d;background:transparent;font:700 14px Nunito;cursor:pointer;color:#42553d}.selected,button:hover{background:#52664c;color:#fff}main{max-width:1140px;margin:auto;padding:35px 24px 80px}article{display:grid;grid-template-columns:300px 1fr;gap:44px;padding:32px 0 48px;border-bottom:1px solid #dedbd0}.media{max-width:300px}.media video{width:100%;aspect-ratio:9/16;display:block;border-radius:15px;background:#1e201d}.media img{width:100%;display:block;border-radius:8px}.controls{display:flex;align-items:center;justify-content:space-between;margin:12px 0}.info{padding:16px 0}h2{font-size:32px;line-height:1.15;margin:8px 0 14px}.angle{color:#69645a}.info p{line-height:1.6}summary{cursor:pointer;font-weight:800;margin:26px 0 10px}pre{font:16px/1.7 Nunito;white-space:pre-wrap;background:#f2efe7;padding:22px;border-radius:12px}.downloads{display:flex;gap:16px;flex-wrap:wrap;font-size:14px}.metric{font-size:13px;color:#69645a}.insight{background:#fff9;border-radius:12px;padding:18px 22px;max-width:890px}footer{padding:20px;text-align:center;font-size:13px}@media(max-width:680px){article{grid-template-columns:1fr;gap:10px}.media{max-width:360px;margin:auto;width:100%}header{padding:32px 24px}h2{font-size:28px}}'''
p.joinpath('index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Everlittle — the next ten</title><style>'+css+'</style><header><div class="eyebrow">EVERLITTLE / CONTENT STUDIO</div><h1>The little things.<br>The next ten.</h1><p>Six short reels made with Google Flow. Four useful carousels. Original hooks, captions and files, in a suggested publishing order.</p><p class="insight"><strong>What the account tells us:</strong> the Grandma meme leads in plays (219), but only seven viewers were reported. No reviewed reel recorded a follow or share. These ten are deliberate tests, not declared viral winners.</p><nav><a class="pill" href="publish-ready.zip" download>Download the batch ↓</a><a class="pill" href="AUDIT.md">Read the audit ↗</a><a class="pill" href="tracking.csv" download>Results tracker ↓</a></nav><nav><button class="selected" onclick="filter(this,\'all\')">All 10</button><button onclick="filter(this,\'reel\')">6 reels</button><button onclick="filter(this,\'carousel\')">4 carousels</button></nav></header><main>'+''.join(cards)+'</main><footer>Prepared for review · Not published · September 2026</footer><script>function slide(b,d){const c=b.closest(".carousel");let n=((Number(c.dataset.slide)-1+d+5)%5)+1;c.dataset.slide=n;c.querySelector("img").src=c.dataset.folder+"/slide-"+String(n).padStart(2,"0")+".png";c.querySelector("span").textContent=n+" / 5"}function filter(b,t){b.parentNode.querySelectorAll("button").forEach(x=>x.classList.toggle("selected",x===b));document.querySelectorAll("article").forEach(a=>a.hidden=t!=="all"&&a.dataset.type!==t)}document.querySelectorAll("video").forEach(v=>v.addEventListener("play",()=>document.querySelectorAll("video").forEach(o=>{if(o!==v)o.pause()})))</script></html>')
print('Gallery ready')
